config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'home#show'
  resource :welcomes, only: %i[create]
  resources :users, only: %i[index]

  namespace :exports, constraints: { format: :csv } do
    resources :users, only: %i[index], controller: :user_informations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/async_log.rb
class AsyncLog < ApplicationRecord
end

app/models/export.rb
require 'csv'

class Export
  def initialize
  end

  def to_users_csv
    CSV.generate(headers: User.attribute_names, write_headers: true) do |csv|
      User.all.each do |user|
        csv << User.attribute_names.map { |attribute| user.send(attribute) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/export_controller_concern.rb
module ExportControllerConcern
  extend ActiveSupport::Concern

  included do
    before_action :load_export
    before_action :export_data
  end

  private

  def load_export
    @export = Export.new
  end

  def send_export_data
    respond_to do |format|
      format.csv { send_data export_data, filename: export_filename }
    end
  end

  def export_data
    raise 'overraide in controller'
  end

  def export_filename
    "#{controller_name}.csv"
  end
end

app/controllers/exports/user_informations_controller.rb
class Exports::UserInformationsController < ApplicationController
  include ExportControllerConcern

  def index
    send_export_data
  end

  private

  def export_data
    @export.to_users_csv
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show ;end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def create
    logger.info 'これからメールを送信します'
    UserMailer.with(email: params[:email], name: params[:name]).welcome.deliver_later
    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exports/user_informations_helper.rb
module Exports::UserInformationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/home/show.html.erb
<%= form_with url: welcomes_path, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.submit 'メール送信'%>
<% end %>

<%= link_to 'ユーザー一覧画面', users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveJobExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= link_to 'CSV出力', exports_users_path(format: :csv) %>